spring:
  cloud:
    config:
      profile: dev
      label: master
      uri: http://localhost:8026/
  application:
    name: config-client
server:
  port: 8027

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/

management:
  security: 
    enabled: false