eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
  healthcheck:
    enabled: true
  instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
      lease-rennewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30
server:
  port: 8016
spring:
  application:
    name: service-hi
  rabbitmq:
    host: 10.0.20.132
    port: 5672
    username: test
    password: test
#  zipkin:
#   base-url: http://localhost:8041
