eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
  healthcheck:
    enabled: true
server:
  port: 8016
spring:
  application:
    name: service-hi
  rabbitmq:
    host: 10.0.20.132
    port: 5672
    username: test
    password: test
#  zipkin:
#   base-url: http://localhost:8041
