eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
server:
  port: 8022
spring:
  application:
    name: service-feign
#  zipkin:
#    base-url: http://localhost:8041
  rabbitmq:
    host: 10.0.20.131
    port: 5672
    username: test
    password: test


feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  15000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000