eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
server:
  port: 8041
spring:
  application:
    name: zipkin-server
  rabbitmq:
    host: 10.0.20.131
    port: 5672
    username: test
    password: test