eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
server:
  port: 8061
spring:
  application:
    name: hystrix-turbine

---
turbine:
  app-config: service-feign
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  combine-host-port: true

---
security:
  basic:
    enabled: false
