eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
server:
  port: 8021
spring:
  application:
    name: service-ribbon
#  zipkin:
#    base-url: http://localhost:8041
  rabbitmq:
    host: 10.0.20.131
    port: 5672
    username: test
    password: test